version: '3.8'

services:
  app:
    build: .
    container_name: gesvet-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gesvetdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

  db:
    image: postgres:15
    container_name: gesvet-db
    environment:
      POSTGRES_DB: gesvetdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - gesvet_data:/var/lib/postgresql/data
    restart: always

volumes:
  gesvet_data:

