

spring.datasource.url=jdbc:mysql://localhost/user
spring.datasource.username=root
spring.datasource.password=
#spring.datasource.password=GesVet1.



spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
logging.level.org.hibernate.SQL = DEBUG
logging.level.org.hibernate.Type = TRACE

#Spring email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=soportegesvet@gmail.com
spring.mail.password=r w z a r z u p w n h w s z i h
spring.mail.properties.mail.smtp.ssl.enable = true
spring.mail.properties.mail.smtp.auth = true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,file:src/main/resources/static/img/imagenes_perfil/

jwt.secret=mySecretKey
jwt.expiration=86400000  # Duraci\u00c3\u00b3n en milisegundos (1 d\u00c3\u00ada en este ejemplo)

# spring.mvc.view.prefix=/WEB-INF/jsp/
