-- MySQL Script generated by MySQL Workbench
-- Thu Oct 12 10:58:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema veterinaria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `veterinaria` ;

-- -----------------------------------------------------
-- Schema veterinaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veterinaria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `veterinaria` ;

-- -----------------------------------------------------
-- Table `veterinaria`.`tipo_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`tipo_categoria` (
  `idTipoC` VARCHAR(10) NOT NULL,
  `nomTipoC` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `veterinaria`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`categoria` (
  `idCategoria` VARCHAR(10) NOT NULL,
  `idTipoCategoria` VARCHAR(45) NOT NULL,
  `nomCategoria` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idCategoria`),
  CONSTRAINT `FKidTipoCategoria`
    FOREIGN KEY (`idTipoCategoria`)
    REFERENCES `veterinaria`.`tipo_categoria` (`idTipoC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKidTipoCategoria_idx` ON `veterinaria`.`categoria` (`idTipoCategoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `veterinaria`.`estado_cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`estado_cita` (
  `idEstadoC` VARCHAR(20) NOT NULL,
  `nomEstadoC` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstadoC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `veterinaria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`clientes` (
  `idClientes` VARCHAR(30) NOT NULL,
  `nomCliente` VARCHAR(45) NOT NULL,
  `apeCliente` VARCHAR(45) NOT NULL,
  `telCliente` VARCHAR(45) NOT NULL,
  `emailCliente` VARCHAR(45) NOT NULL,
  `dirCliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `veterinaria`.`mascotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`mascotas` (
  `idMascotas` VARCHAR(20) NOT NULL,
  `nomMascota` VARCHAR(45) NOT NULL,
  `naciMascota` DATE NOT NULL,
  `razaMascota` VARCHAR(45) NOT NULL,
  `tipoMascota` VARCHAR(45) NOT NULL,
  `FKidClienteMasc` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`idMascotas`),
  CONSTRAINT `FKcliente_mascota`
    FOREIGN KEY (`FKidClienteMasc`)
    REFERENCES `veterinaria`.`clientes` (`idClientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKcliente_mascota_idx` ON `veterinaria`.`mascotas` (`FKidClienteMasc` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `veterinaria`.`medico_vet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`medico_vet` (
  `idMedicoVet` VARCHAR(30) NOT NULL,
  `nomVet` VARCHAR(45) NULL DEFAULT NULL,
  `apeVet` VARCHAR(45) NULL DEFAULT NULL,
  `telVet` VARCHAR(45) NULL DEFAULT NULL,
  `emailVet` VARCHAR(45) NULL DEFAULT NULL,
  `dirVet` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idMedicoVet`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `veterinaria`.`citas_consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`citas_consultas` (
  `idCita` VARCHAR(20) NOT NULL,
  `idCita_mascota` VARCHAR(30) NOT NULL,
  `idCita_veterinario` VARCHAR(30) NOT NULL,
  `idCita_estadoC` VARCHAR(45) NOT NULL,
  `fechaC` DATE NOT NULL,
  `motivoCita` VARCHAR(200) NOT NULL,
  `diagnostico` VARCHAR(200) NULL DEFAULT NULL,
  `formula` VARCHAR(100) NULL DEFAULT NULL,
  `alertaCita` DATE NOT NULL,
  PRIMARY KEY (`idCita`),
  CONSTRAINT `FK-cita_estadoC`
    FOREIGN KEY (`idCita_estadoC`)
    REFERENCES `veterinaria`.`estado_cita` (`idEstadoC`),
  CONSTRAINT `FK-mascota_Cita`
    FOREIGN KEY (`idCita_mascota`)
    REFERENCES `veterinaria`.`mascotas` (`idMascotas`),
  CONSTRAINT `FK-veterinario_Cita`
    FOREIGN KEY (`idCita_veterinario`)
    REFERENCES `veterinaria`.`medico_vet` (`idMedicoVet`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK-veterinarioCita_idx` ON `veterinaria`.`citas_consultas` (`idCita_veterinario` ASC) VISIBLE;

CREATE INDEX `FK-mascotaCita_idx` ON `veterinaria`.`citas_consultas` (`idCita_mascota` ASC) VISIBLE;

CREATE INDEX `FK-cita_estadoC_idx` ON `veterinaria`.`citas_consultas` (`idCita_estadoC` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `veterinaria`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`proveedor` (
  `idProveedores` VARCHAR(30) NOT NULL,
  `nomProv` VARCHAR(45) NOT NULL,
  `apeProv` VARCHAR(45) NOT NULL,
  `telProv` VARCHAR(45) NOT NULL,
  `emailProv` VARCHAR(45) NOT NULL,
  `dirProv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveedores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `veterinaria`.`factura_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`factura_compra` (
  `idFactura_compra` VARCHAR(20) NOT NULL,
  `idProvFactC` VARCHAR(45) NOT NULL,
  `fechaCompra` DATE NOT NULL,
  PRIMARY KEY (`idFactura_compra`),
  CONSTRAINT `FK-provFactCompra`
    FOREIGN KEY (`idProvFactC`)
    REFERENCES `veterinaria`.`proveedor` (`idProveedores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK-provFactCompra_idx` ON `veterinaria`.`factura_compra` (`idProvFactC` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `veterinaria`.`detalle_fact_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`detalle_fact_compra` (
  `idDetalleCompra` VARCHAR(30) NOT NULL,
  `idDetFactC_factC` VARCHAR(45) NOT NULL,
  `cantCompra` INT NOT NULL,
  `precioCompra` DECIMAL(15,2) NOT NULL,
  `ultimoPCompra` DECIMAL(12,5) NOT NULL,
  PRIMARY KEY (`idDetalleCompra`),
  CONSTRAINT `FK_detCompra_factCompra`
    FOREIGN KEY (`idDetFactC_factC`)
    REFERENCES `veterinaria`.`factura_compra` (`idFactura_compra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK-factComp_detFComp_idx` ON `veterinaria`.`detalle_fact_compra` (`idDetFactC_factC` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `veterinaria`.`factura_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`factura_venta` (
  `idFactura_venta` VARCHAR(20) NOT NULL,
  `idFactV_cliente` VARCHAR(45) NOT NULL,
  `fechaVenta` DATE NOT NULL,
  PRIMARY KEY (`idFactura_venta`),
  CONSTRAINT `FK-cliente_facturaV`
    FOREIGN KEY (`idFactV_cliente`)
    REFERENCES `veterinaria`.`clientes` (`idClientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK-cliente_facturaV_idx` ON `veterinaria`.`factura_venta` (`idFactV_cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `veterinaria`.`medio_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`medio_pago` (
  `idPago` VARCHAR(10) NOT NULL,
  `nomPago` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `veterinaria`.`tipo_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`tipo_servicio` (
  `idTipoServicio` VARCHAR(10) NOT NULL,
  `nomServicio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoServicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `veterinaria`.`productos_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`productos_servicios` (
  `idProdServ` VARCHAR(20) NOT NULL,
  `idProd_categoria` VARCHAR(20) NOT NULL,
  `idProd_detFactC` VARCHAR(20) NULL DEFAULT NULL,
  `nomProdServ` VARCHAR(45) NOT NULL,
  `presProdServ` VARCHAR(100) NOT NULL,
  `precioVenta` DECIMAL(15,2) NOT NULL,
  `existProd` INT NULL DEFAULT NULL,
  `ultimoPVenta` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idProdServ`),
  CONSTRAINT `FK-prodServ_cat`
    FOREIGN KEY (`idProd_categoria`)
    REFERENCES `veterinaria`.`categoria` (`idCategoria`),
  CONSTRAINT `FK-prodServ_detFactC`
    FOREIGN KEY (`idProd_detFactC`)
    REFERENCES `veterinaria`.`detalle_fact_compra` (`idDetalleCompra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK-prodServ_cat_idx` ON `veterinaria`.`productos_servicios` (`idProd_categoria` ASC) VISIBLE;

CREATE INDEX `FK-prodServ_detFactC_idx` ON `veterinaria`.`productos_servicios` (`idProd_detFactC` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `veterinaria`.`detalle_fact_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`detalle_fact_venta` (
  `idDetalle_venta` VARCHAR(20) NOT NULL,
  `idDetaFactV_facturaV` VARCHAR(45) NOT NULL,
  `idDetFactV_prod` VARCHAR(45) NOT NULL,
  `idDetFactV_tServicio` VARCHAR(45) NOT NULL,
  `idDetFactV_medioP` VARCHAR(45) NOT NULL,
  `cantVenta` INT NOT NULL,
  PRIMARY KEY (`idDetalle_venta`),
  CONSTRAINT `FK-detFactV-facturaV`
    FOREIGN KEY (`idDetaFactV_facturaV`)
    REFERENCES `veterinaria`.`factura_venta` (`idFactura_venta`),
  CONSTRAINT `FK-detFactV-medioP`
    FOREIGN KEY (`idDetFactV_medioP`)
    REFERENCES `veterinaria`.`medio_pago` (`idPago`),
  CONSTRAINT `FK-detFactV-tipoS`
    FOREIGN KEY (`idDetFactV_tServicio`)
    REFERENCES `veterinaria`.`tipo_servicio` (`idTipoServicio`),
  CONSTRAINT `FK-detFactV_prodServ`
    FOREIGN KEY (`idDetFactV_prod`)
    REFERENCES `veterinaria`.`productos_servicios` (`idProdServ`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK-tServVenta_idx` ON `veterinaria`.`detalle_fact_venta` (`idDetFactV_tServicio` ASC) VISIBLE;

CREATE INDEX `FK-detFactVenta_medioP_idx` ON `veterinaria`.`detalle_fact_venta` (`idDetFactV_medioP` ASC) VISIBLE;

CREATE INDEX `FK-detFactV-facturaV_idx` ON `veterinaria`.`detalle_fact_venta` (`idDetaFactV_facturaV` ASC) VISIBLE;

CREATE INDEX `FK-detFactV_prodServ_idx` ON `veterinaria`.`detalle_fact_venta` (`idDetFactV_prod` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `veterinaria`.`tipo_vacunas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`tipo_vacunas` (
  `idTipoVacuna` VARCHAR(20) NOT NULL,
  `nomVacuna` VARCHAR(50) NOT NULL,
  `descVacuna` VARCHAR(200) NOT NULL,
  `precioVacuna` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`idTipoVacuna`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `veterinaria`.`vacunas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`vacunas` (
  `idVacuna` VARCHAR(20) NOT NULL,
  `idVacuna_Mascota` VARCHAR(45) NOT NULL,
  `idVacuna_tipoS` VARCHAR(45) NOT NULL,
  `idVacuna_vet` VARCHAR(45) NOT NULL,
  `idVacuna_medioP` VARCHAR(45) NOT NULL,
  `idVacuna_tipoV` VARCHAR(45) NOT NULL,
  `fechaVac` DATE NOT NULL,
  `fechaProxV` DATE NOT NULL,
  `alerta` DATE NOT NULL,
  PRIMARY KEY (`idVacuna`),
  CONSTRAINT `FK-vacuna_medioP`
    FOREIGN KEY (`idVacuna_medioP`)
    REFERENCES `veterinaria`.`medio_pago` (`idPago`),
  CONSTRAINT `FK-vacuna_tipoV`
    FOREIGN KEY (`idVacuna_tipoV`)
    REFERENCES `veterinaria`.`tipo_vacunas` (`idTipoVacuna`),
  CONSTRAINT `FK-vacuna_veterinario`
    FOREIGN KEY (`idVacuna_vet`)
    REFERENCES `veterinaria`.`medico_vet` (`idMedicoVet`),
  CONSTRAINT `FKvacunaMascota`
    FOREIGN KEY (`idVacuna_Mascota`)
    REFERENCES `veterinaria`.`mascotas` (`idMascotas`),
  CONSTRAINT `FKvacunaServicio`
    FOREIGN KEY (`idVacuna_tipoS`)
    REFERENCES `veterinaria`.`tipo_servicio` (`idTipoServicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKvacunaMascota_idx` ON `veterinaria`.`vacunas` (`idVacuna_Mascota` ASC) VISIBLE;

CREATE INDEX `FKvacunaServicio_idx` ON `veterinaria`.`vacunas` (`idVacuna_tipoS` ASC) VISIBLE;

CREATE INDEX `FK-vacuna_veterinario_idx` ON `veterinaria`.`vacunas` (`idVacuna_vet` ASC) VISIBLE;

CREATE INDEX `FK-vacuna_medioP_idx` ON `veterinaria`.`vacunas` (`idVacuna_medioP` ASC) VISIBLE;

CREATE INDEX `FK-vacuna_tipoV_idx` ON `veterinaria`.`vacunas` (`idVacuna_tipoV` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
